# Generated by Django 6.0 on 2025-12-27 00:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('matric_number', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('faculty', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('year_of_graduation', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_type', models.CharField(choices=[('B.Sc', 'Bachelor of Science'), ('B.A', 'Bachelor of Arts'), ('M.Sc', 'Master of Science'), ('M.A', 'Master of Arts'), ('PhD', 'Doctor of Philosophy'), ('PGD', 'Post Graduate Diploma'), ('HND', 'higher National Diploma'), ('OND ', 'Ordinary National Diploma')], default='B.Sc', max_length=50)),
                ('classification', models.CharField(choices=[('First Class', 'First Class Honours'), ('Second Class Upper', 'Second Class Hons. Upper Division'), ('Second Class Lower', 'Second Class Hons. Lower Division'), ('Third Class', 'Third Class'), ('Pass', 'Pass')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_name', models.CharField(max_length=200)),
                ('date_of_issue', models.DateField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='certificate.student')),
            ],
            options={
                'ordering': ['date_of_issue'],
            },
        ),
    ]
