# Generated by Django 6.0 on 2026-01-06 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='graduation_date',
            field=models.DateField(default=datetime.date(2026, 1, 1)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificate',
            name='classification',
            field=models.CharField(choices=[('First Class Honours', 'First Class Honours'), ('Second Class Hons. Upper Division', 'Second Class Hons. Upper Division'), ('Second Class Hons. Lower Division', 'Second Class Hons. Lower Division'), ('Third Class', 'Third Class'), ('Pass', 'Pass')], max_length=50),
        ),
    ]
