# Generated by Django 6.0 on 2026-01-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0002_student_graduation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_type',
            field=models.CharField(choices=[('B.Sc.', 'Bachelor of Science'), ('B.A', 'Bachelor of Arts'), ('M.Sc', 'Master of Science'), ('M.A', 'Master of Arts'), ('PhD', 'Doctor of Philosophy'), ('PGD', 'Post Graduate Diploma'), ('HND', 'higher National Diploma'), ('OND ', 'Ordinary National Diploma')], default='B.Sc', max_length=50),
        ),
    ]
