# Generated by Django 6.0 on 2026-01-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0004_certificate_certificate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_id',
            field=models.CharField(editable=False, max_length=30, unique=True),
        ),
    ]
