# Generated by Django 6.0 on 2026-04-07 10:09

import certificate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0006_certificate_digital_signature_certificate_qr_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='digital_signature',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='qr_code',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=certificate.models.qr_upload_path),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='verification_token',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
    ]
