# Generated by Django 6.0 on 2026-06-02 17:23

import certificate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0007_alter_certificate_digital_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to=certificate.models.certificate_file_upload_path),
        ),
    ]
