# Generated by Django 6.0 on 2026-06-15 11:01

import certificate.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0008_certificate_certificate_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='matric_number',
            field=models.CharField(max_length=50, unique=True, validators=[certificate.models.validate_matric]),
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.UniqueConstraint(fields=('student', 'certificate_type', 'course_name'), name='unique_certificate_per_program'),
        ),
    ]
