# Generated by Django 6.0 on 2026-06-15 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0009_alter_student_matric_number_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='certificate',
            name='unique_certificate_per_program',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='certificate.student'),
        ),
    ]
