# Generated by Django 6.0 on 2026-06-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0010_remove_certificate_unique_certificate_per_program_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='course_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
